"""add icon_url

Revision ID: 89a9cef18f06
Revises: 2adc36df856e
Create Date: 2017-11-13 19:12:47.744668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89a9cef18f06'
down_revision = '2adc36df856e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('icon_url', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'icon_url')
    # ### end Alembic commands ###
