"""add friends

Revision ID: db4968b8e01f
Revises: 04c7aae1066b
Create Date: 2017-11-09 22:37:40.615193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4968b8e01f'
down_revision = '04c7aae1066b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_Tasks_tag'), 'Tasks', ['tag'], unique=False)
    op.drop_index('ix_Tasks_tag', table_name='Tasks')
    op.add_column('Users', sa.Column('friends', sa.INTEGER(), nullable=True))
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_username'), 'Users', ['username'], unique=True)
    op.drop_index('ix_Users_email', table_name='Users')
    op.drop_index('ix_Users_username', table_name='Users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Users_username', 'Users', ['username'], unique=True)
    op.create_index('ix_Users_email', 'Users', ['email'], unique=True)
    op.drop_index(op.f('ix_Users_username'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_column('Users', 'friends')
    op.create_index('ix_Tasks_tag', 'Tasks', ['tag'], unique=False)
    op.drop_index(op.f('ix_Tasks_tag'), table_name='Tasks')
    # ### end Alembic commands ###
